[package]
name = "latte"
description = "Cassandra Latency and Throughput Tester. Runs CQL queries in parallel, measures performance and computes useful statistics."
version = "0.5.0"
authors = ["Piotr Kołaczkowski <pkolaczk@datastax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.test]
opt-level = 2

[dependencies]
async-trait = "0.1.41"
atomic-counter = "1.0.1"
cassandra-cpp = "0.15.1"
chrono = "0.4.18"
clap = "3.0.0-beta.2"
console = "0.11.2"
cpu-time = "1.0.0"
err-derive = "0.2.4"
futures = { version = "0.3.6" }
hdrhistogram = "7.1.0"
indicatif = "0.15.0"
itertools = "0.9.0"
num_cpus = "1.13.0"
rand = "0.7.3"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
statrs = "0.13.0"
strum = { version = "0.19.5", features = ["derive"] }
strum_macros = "0.19.4"
tokio = { version = "0.3.1", features = ["rt", "rt-multi-thread", "time", "stream"] }
time = "0.1.44"
